### ISSUE TITLE
Running this image in AWS ECS or EC2 do not validate emails.

### ISSUE THREAD

**Issue by Tdnshah** [truemail-rb/truemail-rack-docker-image#19]
### New Issue Checklist

- [x] I have used the latest version of Truemail rack docker image
- [x] I have read the [Contribution Guidelines](https://github.com/truemail-rb/truemail-rack-docker-image/blob/master/CONTRIBUTING.md)
- [x] I have read the [documentation](https://github.com/truemail-rb/truemail-rack-docker-image/blob/master/README.md)
- [x] I have searched for [existing GitHub issues](https://github.com/truemail-rb/truemail-rack-docker-image/issues)

### Issue Description
Running this docker image in an AWS EC2 or ECS   instance do not validate the email and get and error as below.

Input Command Used for running the container

<pre>docker run -it -p 9292:9292 -e VERIFIER_EMAIL='demo@gmail.com' -e ACCESS_TOKENS='validtoken' truemail/truemail-rack</pre>

##### Complete output of the api response is as below:
<details>
  <pre>{
    "date": "2020-11-01 10:49:42 +0000",
    "email": "somevalidaddress@gmail.com",
    "validation_type": "smtp",
    "success": false,
    "errors": {
        "smtp": "smtp error"
    },
    "smtp_debug": [
        {
            "mail_host": "142.250.112.27",
            "port_opened": false,
            "connection": null,
            "errors": {}
        },
        {
            "mail_host": "173.194.215.26",
            "port_opened": false,
            "connection": null,
            "errors": {}
        },
        {
            "mail_host": "64.233.186.27",
            "port_opened": false,
            "connection": null,
            "errors": {}
        },
        {
            "mail_host": "209.85.202.26",
            "port_opened": false,
            "connection": null,
            "errors": {}
        },
        {
            "mail_host": "64.233.184.27",
            "port_opened": false,
            "connection": null,
            "errors": {}
        }
    ],
    "configuration": {
        "validation_type_by_domain": null,
        "whitelist_validation": false,
        "whitelisted_domains": null,
        "blacklisted_domains": null,
        "not_rfc_mx_lookup_flow": false,
        "smtp_safe_check": false,
        "email_pattern": "default gem value",
        "smtp_error_body_pattern": "default gem value"
    }
}</pre>
</details>

**Comment by bestwebua** [comment]
Hello, @Tdnshah! You should contact aws support to open 25 port before. Cheers!
