### ISSUE TITLE
[QUESTION] Required ACCESS_TOKENS details

### ISSUE THREAD

**Issue by aishusubramanian13** [truemail-rb/truemail-rack-docker-image#58]
### New question checklist

- [x] I have read the [Contribution Guidelines](https://github.com/truemail-rb/truemail-rack-docker-image/blob/master/CONTRIBUTING.md)
- [x] I have read the [documentation](https://truemail-rb.org/truemail-rack-docker-image)
- [x] I have searched for [existing GitHub issues](https://github.com/truemail-rb/truemail-rack-docker-image/issues)

### Question

Kindly let me know how to get the access token details for setup the truemail-rack-docker-image - https://github.com/truemail-rb/truemail-rack-docker-image

I would like to validate the email using the truemail-rack-docker.

I have pull the docker image and set the VERIFIER_EMAIL in docker-compose.yml file. But i dont know the value for access token and I don't have the knowledge about how/where to get the access token details.

Thanks in advanced.

**Comment by aishusubramanian13** [comment]
> Hi, @aishusubramanian13! It can be some string provided from you. About `ACCESS_TOKENS` var you can find a lot here: https://truemail-rb.org/truemail-rack/#/starting-the-server?id=configurable-options
Thanks for the response. 
I am not sure about any string. it can be token from github/ SMTP token/ Docker token or any random string?

**Comment by bestwebua** [comment]
> Thanks for the response.
> I am not sure about any string. it can be token from github/ SMTP token/ Docker token or any random string?

It can be a random string.
