### ISSUE TITLE
[BUG] All emails validations are sending key as success as false with SMTP Error

### ISSUE THREAD

**Issue by shivaprasad573** [truemail-rb/truemail-rack-docker-image#64]
### New bug checklist

- [x] I have used the latest version of Truemail rack docker image
- [x] I have read the [Contribution Guidelines](https://github.com/truemail-rb/truemail-rack-docker-image/blob/master/CONTRIBUTING.md)
- [x] I have read the [documentation](https://truemail-rb.org/truemail-rack-docker-image)
- [x] I have searched for [existing GitHub issues](https://github.com/truemail-rb/truemail-rack-docker-image/issues)

All email validations are sent as success key as false with SMTP Error

### Bug description
I am using docker-compose to run the truemail serer. Please find the bellow image for docker-compose.yml file and 

![Screenshot from 2022-12-08 10-58-08](https://user-images.githubusercontent.com/12299919/206366743-bef4dcd0-db90-4412-9dd4-82db058a5ea5.png)

I was using below command to start the truemail
`sudo docker-compose up -d`

##### Complete output when running truemail, including the stack trace and command used

Then am using a java client for validating the emails please find the below image and response that I am receding.
![Screenshot 08-12-2022 at 11 01 AM](https://user-images.githubusercontent.com/12299919/206366987-c8e07e4e-4826-4eb6-884b-adfd7127677d.png)

##### Complete output when running truemail API in browser
When I use Web request to validate the email am getting the {"error":"resource not found"}  error. Please find the bellow screenshot.

![Screenshot from 2022-12-08 11-14-04](https://user-images.githubusercontent.com/12299919/206367362-9c76cffb-fd4d-4047-82e3-ae68097ba4d6.png)

Please let me know if am missing anything

**Comment by bestwebua** [comment]
@shivaprasad573 Please provide result with full smtp_debug. It's not a truemail-rack-docker-image question.

> Complete output when running truemail API in browser

You have used wrong API endpoint, please check the documentation before: https://truemail-rb.org/truemail-rack/#/endpoints

**Comment by shivaprasad573** [comment]
Thank you for responding and using the above end point I have  made a request and here is the full log.

curl -i -H "Accept: application/json" -H "Content-Type: application/json" -H "Authorization: Token" http://localhost:9292?email=Validemail@domain.com


`{"date":"2022-12-08 09:55:49 +0000","email":"<validemail>","validation_type":"smtp","success":false,"errors":{"smtp":"smtp error"},"smtp_debug":[{"mail_host":"198.38.82.72","port_opened":false,"connection":null,"errors":{}}],"configuration":{"validation_type_by_domain":null,"whitelist_validation":false,"whitelisted_emails":null,"blacklisted_emails":null,"whitelisted_domains":null,"blacklisted_domains":null,"blacklisted_mx_ip_addresses":null,"dns":null,"not_rfc_mx_lookup_flow":false,"smtp_fail_fast":false,"smtp_safe_check":false,"email_pattern":"default gem value","smtp_error_body_pattern":"default gem value"}}`

**Comment by bestwebua** [comment]
@shivaprasad573 Please look here: `"port_opened":false`. I think that 25 port for openning connections is forbidden on your host.

**Comment by shivaprasad573** [comment]
I have checked and our port is open  and able to connect 

Port 25 is open telnet 198.38.82.72 25Trying 198.38.82.72...Connected to 198.38.82.72.Escape character is '^]'.

**Comment by shivaprasad573** [comment]
**Sometimes it is throwing saying "connection": false **
Here am using the same domain as my VERIFIER_EMAIL 

`
{
  "date": "2022-12-08 11:31:00 +0000",
  "email": "shxxxxxx@yyyyycs.ai",
  "validation_type": "smtp",
  "success": false,
  "errors": {
    "smtp": "smtp error"
  },
  "smtp_debug": [
    {
      "mail_host": "198.zz.yy.xx",
      "port_opened": true,
      "connection": false,
      "errors": {
        "connection": "server response timeout"
      }
    }
  ],
  "configuration": {
    "validation_type_by_domain": null,
    "whitelist_validation": false,
    "whitelisted_emails": null,
    "blacklisted_emails": null,
    "whitelisted_domains": null,
    "blacklisted_domains": null,
    "blacklisted_mx_ip_addresses": null,
    "dns": null,
    "not_rfc_mx_lookup_flow": false,
    "smtp_fail_fast": false,
    "smtp_safe_check": false,
    "email_pattern": "default gem value",
    "smtp_error_body_pattern": "default gem value"
  }
}
`

**Sometimes saying it as connection is true  and success also true**
Here am using the public domain as my GMAIL 
`
{
  "date": "2022-12-08 11:36:17 +0000",
  "email": "yyyyyyy@gmail.com",
  "validation_type": "smtp",
  "success": true,
  "errors": null,
  "smtp_debug": null,
  "configuration": {
    "validation_type_by_domain": null,
    "whitelist_validation": false,
    "whitelisted_emails": null,
    "blacklisted_emails": null,
    "whitelisted_domains": null,
    "blacklisted_domains": null,
    "blacklisted_mx_ip_addresses": null,
    "dns": null,
    "not_rfc_mx_lookup_flow": false,
    "smtp_fail_fast": false,
    "smtp_safe_check": false,
    "email_pattern": "default gem value",
    "smtp_error_body_pattern": "default gem value"
  }
}
`

**Comment by bestwebua** [comment]
Okay. Did you complete all this preconditions? https://truemail-rb.org/truemail-gem/#/quick-start?id=verifier-host-preconditions Seems like your host looks like untrusted for email provider side...

**Comment by shivaprasad573** [comment]
Thank you for your quick response @bestwebua  I think I need some clarity on the below point in preconditions.
**Verifier domain should refer to [verefier host] IP address**

Our website is deployed in Azure (Domain is pointed to Azure IP)  and we are using a Shared email hosting from Mochahost.  This means we have run the truemail in Azure where we deployed our website am I correct?

**Comment by bestwebua** [comment]
@shivaprasad573 Yes.

**Comment by FatihK27** [comment]
Does it mean we can't test Truemail docker image on our local pc, right? I asked this because I am trying to test docker image on my local pc and docker desktop but I am getting error message in result as "port_opened:false". I couldn't verified any mail.

**Comment by bestwebua** [comment]
@FatihK27 port_opened:false - seems like it is a question for your local internet provider.

**Comment by mieshalannair** [comment]
@bestwebua I'm aware that many ISPs block port 25, and [AWS](https://postmarkapp.com/support/article/1026-resolving-aws-port-25-throttling#:~:text=Amazon%20Web%20Services'%20EC2%20instances,Postmark%20in%20your%20EC2%20instance.) has also taken this measure by default to reduce the volume of spam emails.

Could you please advise me on how to transition to port 465 or 2525 ? Despite setting SMTP_PORT to one of these values, I'm encountering an error. Is there something I might be overlooking?

Thank you in advance for your guidance.

**Comment by FatihK27** [comment]
> @bestwebua I'm aware that many ISPs block port 25, and [AWS](https://postmarkapp.com/support/article/1026-resolving-aws-port-25-throttling#:~:text=Amazon%20Web%20Services'%20EC2%20instances,Postmark%20in%20your%20EC2%20instance.) has also taken this measure by default to reduce the volume of spam emails.
> 
> Could you please advise me on how to transition to port 465 or 2525 ? Despite setting SMTP_PORT to one of these values, I'm encountering an error. Is there something I might be overlooking?
> 
> Thank you in advance for your guidance.

I think you should ask your service provider if the port is really open. Majority of providers restrict port forwarding and as far as I know you need to static ip address. In the past I faced to problem when I trying to verifying mail address I was getting error message in result as "port_opened:false" because of my internet service provider. When I move my project on the any cloud provider for test purposes I had verified email adresses successfully with truemail.
