### ISSUE TITLE
[QUESTION] Is there any additional SMTP configurations I should set for validating yahoo mail addresses?

### ISSUE THREAD

**Issue by shrestsav** [truemail-rb/truemail-rack-docker-image#80]
### New question checklist

- [x] I have read the [Contribution Guidelines](https://github.com/truemail-rb/truemail-rack-docker-image/blob/master/CONTRIBUTING.md)
- [x] I have read the [documentation](https://truemail-rb.org/truemail-rack-docker-image)
- [x] I have searched for [existing GitHub issues](https://github.com/truemail-rb/truemail-rack-docker-image/issues)

### Question
Hy, I have a question regarding validating Yahoo mail addresses or other mail addresses other than Gmail. While I validate gmail addresses it works flawlessly.
![image](https://user-images.githubusercontent.com/14362314/229769210-ebe4ff26-01eb-4c39-bc6d-44b3fa787d35.png)

But when I try to check emails from other domains like yahoo or other, the response is quite inconsistent. For yahoo emails, it just returns true (i.e email exists) for any random emails e.g: fajsdkfjalskdfjlkjd23234@yahoo.com
e.g:
### This actually exists testemail@utsavshrestha.com.np
![image](https://user-images.githubusercontent.com/14362314/229768577-d8758026-a9e3-40f8-8f88-e9520b6da326.png)

### This exists too utsav@kvsocial.com
![image](https://user-images.githubusercontent.com/14362314/229769517-da81f20f-3e26-444e-8771-50151b861210.png)

###

**Comment by bestwebua** [comment]
@shrestsav I believe that you can read our docs: https://truemail-rb.org/truemail-gem/#/quick-start
P.S.: yahoo/aol return successful result for any email.
